networks:
  spark-net:
    driver: bridge

services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: bigdata
      POSTGRES_USER: spark
      POSTGRES_PASSWORD: spark123
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - "./исходные данные:/docker-entrypoint-initdb.d/data"
      - pg_data:/var/lib/postgresql/data
    networks:
      - spark-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spark -d bigdata"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-master:
    image: apache/spark:3.5.5
    container_name: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./jobs:/opt/spark/work-dir
    networks:
      - spark-net
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "0.0.0.0"]

  spark-worker:
    image: apache/spark:3.5.5
    container_name: spark-worker
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    volumes:
      - ./jobs:/opt/spark/work-dir
    networks:
      - spark-net
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]

  clickhouse:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - spark-net
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse-init:
    image: clickhouse/clickhouse-client:24
    container_name: clickhouse-init
    depends_on:
      clickhouse:
        condition: service_healthy
    volumes:
      - ./clickhouse-init:/init-scripts
    entrypoint: ["/bin/bash", "/init-scripts/run_init.sh"]
    networks:
      - spark-net

  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/neo4j123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - spark-net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  pg_data:
  ch_data:
  neo4j_data:
  neo4j_logs:
